import { StakePoolCreationFlow } from '@/components/stake-pool-creation/StakePoolCreationFlow'
import { HeaderSlim } from 'common/HeaderSlim'
import Head from 'next/head'

const AdminCreatePage = () => {
  return (
    <>
      <Head>
        <title>Cardinal Staking UI</title>
        <meta name="description" content="Generated by Cardinal Staking UI" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          data-domain="stake.cardinal.so"
          src="https://plausible.io/js/plausible.js"
        ></script>
      </Head>

      <HeaderSlim />
      <div className="container mx-auto w-full flex-grow px-6">
        <StakePoolCreationFlow />
      </div>
    </>
  )
}

export default AdminCreatePage
