import { Footer } from 'common/Footer'
import { HeaderSlim } from 'common/HeaderSlim'
import { StakePoolCreationFlow } from 'components/stake-pool-creation/StakePoolCreationFlow'
// import { StakePoolForm } from 'components/StakePoolForm'
import Head from 'next/head'

export function Placeholder() {
  return (
    <div className="h-[300px] animate-pulse rounded-lg bg-white bg-opacity-5 p-10"></div>
  )
}

function Admin() {
  return (
    <div className="">
      <Head>
        <title>Cardinal Staking UI</title>
        <meta name="description" content="Generated by Cardinal Staking UI" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          data-domain="stake.cardinal.so"
          src="https://plausible.io/js/plausible.js"
        ></script>
      </Head>

      <HeaderSlim />
      <div className="container mx-auto -mt-8 h-screen w-full">
        <StakePoolCreationFlow handleSubmit={() => {}} />
      </div>
      <Footer />
    </div>
  )
}

export default Admin
