import { FooterSlim } from 'common/FooterSlim'
import { HeaderSlim } from 'common/HeaderSlim'
import { StakePoolCreationFlow } from 'components/stake-pool-creation/StakePoolCreationFlow'
import Head from 'next/head'

import { AdminPools } from './AdminPools'

function Admin() {
  return (
    <div>
      <Head>
        <title>Cardinal Staking UI</title>
        <meta name="description" content="Generated by Cardinal Staking UI" />
        <link rel="icon" href="/favicon.ico" />
        <script
          defer
          data-domain="stake.cardinal.so"
          src="https://plausible.io/js/plausible.js"
        ></script>
      </Head>

      <HeaderSlim />
      <div className="container mx-auto w-full px-10">
        <StakePoolCreationFlow />
        <AdminPools />
      </div>
      <FooterSlim />
    </div>
  )
}

export default Admin
