import { useWallet } from '@solana/wallet-adapter-react'
import { Header } from 'common/Header'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useUserTokenData } from 'providers/TokenDataProvider'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

function Admin() {
  const { setAddress, tokenDatas, loaded, refreshing } = useUserTokenData()
  const wallet = useWallet()

  useEffect(() => {
    if (wallet && wallet.connected && wallet.publicKey) {
      setAddress(wallet.publicKey.toBase58())
    }
  }, [wallet.publicKey])

  const FormFieldTitleInput = (props: {
    title: string
    htmlFor: string
    description: string
    placeholder: string
  }) => (
    <>
      <label
        className="mb-2 block inline-block text-xs font-bold uppercase tracking-wide text-gray-200"
        htmlFor={props.htmlFor}
      >
        {props.title}
      </label>
      <p className="mb-2 text-sm italic text-gray-300">{props.description}</p>
      <input
        className="mb-3 block w-full appearance-none rounded border border-gray-500 bg-gray-700 py-3 px-4 leading-tight text-gray-200 focus:bg-gray-800 focus:outline-none"
        id={props.htmlFor}
        type="text"
        placeholder={props.placeholder}
      />
    </>
  )

  return (
    <div>
      <Head>
        <title>Cardinal Staking UI</title>
        <meta name="description" content="Generated by Cardinal Staking UI" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="container mx-auto max-h-[90vh] w-full bg-[#1a1b20]">
          <Header />
          <div className="my-2 grid h-full grid-cols-1 gap-4">
            <div className="rounded-md bg-white bg-opacity-5 p-10 text-gray-200">
              <p className="text-lg font-bold">Create Staking Pool</p>
              <p className="mt-1 mb-2 text-sm">
                All parameters for staking pool are optional
              </p>
              <form className="w-full max-w-lg">                
                <div className="-mx-3 flex flex-wrap">
                  <div className="mb-6 mt-4 w-full px-3 md:mb-0">
                    <FormFieldTitleInput
                      title={'Overlay Text'}
                      htmlFor={'overlay-text'}
                      description={'Text to display over the rental receipt'}
                      placeholder={'RENTED'}
                    />
                  </div>
                </div>
                <div className="-mx-3 flex flex-wrap">
                  <div className="mb-6 mt-4 w-full px-3 md:mb-0">
                    <FormFieldTitleInput
                      title={'Collection Addresses []'}
                      htmlFor={'collection-addresses'}
                      description={
                        'Only allow NFTs with these collection addresses'
                      }
                      placeholder={'Cmwy..., A3fD...'}
                    />
                  </div>
                </div>
                <div className="-mx-3 flex flex-wrap">
                  <div className="mb-6 mt-4 w-full px-3 md:mb-0">
                    <FormFieldTitleInput
                      title={'Creator Addresses []'}
                      htmlFor={'creator-addresses'}
                      description={
                        'Only allow NFTs with these creator addresses'
                      }
                      placeholder={'Cmwy..., A3fD...'}
                    />
                  </div>
                </div>
                <div className="-mx-3 flex flex-wrap">
                  <div className="mb-6 mt-4 w-full px-3 md:mb-0">
                    <label
                      className="mb-2 block inline-block text-xs font-bold uppercase tracking-wide text-gray-200"
                      htmlFor="require-authorization"
                    >
                      Authorize NFTs
                    </label>
                    <p className="mb-2 text-sm italic text-gray-300">
                      If selected, NFTs must be authorized on-chain before entering the pool  
                    </p>
                    <input
                      className="mb-3"
                      id="require-authorization"
                      type="checkbox"
                      
                    /> <span className="text-sm my-auto">Require Authorization</span>
                  </div>
                </div>
                <button className="mt-4 rounded-md bg-blue-700 px-4 py-2">
                  Create Pool
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Admin
