import { Header } from 'common/Header'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Cardinal Staking UI</title>
        <meta name="description" content="Generated by Cardinal Staking UI" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="container mx-auto w-full bg-[#1a1b20]">
          <Header />
          <div className="my-2 grid grid-cols-2 gap-4">
            <div className="rounded-md bg-white bg-opacity-5 p-10 text-gray-200">
              <p className="text-lg">Select your NFTs</p>
            </div>
            <div className="rounded-md bg-white bg-opacity-5 p-10 text-gray-200">
              <p className="text-lg">View Staked NFTs</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
